/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-09-27

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include "stm32l1xx.h"


/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */



/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
int main(void)
{
	int i = 0;

	/**
	 *  IMPORTANT NOTE!
	 *  See the <system_*.c> file and how/if the SystemInit() function updates
	 *  SCB->VTOR register. Sometimes the symbol VECT_TAB_SRAM needs to be defined
	 *  when building the project if code has been located to RAM and interrupts
	 *  are used. Otherwise the interrupt table located in flash will be used.
	 *  E.g.  SCB->VTOR = 0x20000000;
	 */

	/**
	 *  At this stage the microcontroller clock setting is already configured,
	 *  this is done through SystemInit() function which is called from startup
	 *  file (startup_stm32l1xx_hd.s) before to branch to application main.
	 *  To reconfigure the default setting of SystemInit() function, refer to
	 *  system_stm32l1xx.c file
	 */

	/* TODO - Add your application code here */
	//1 uloha:
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA, ENABLE);
	GPIOA->MODER |= (uint32_t) 0b01<<(5*2);
	//GPIOA->OTYPER
	GPIOA->PUPDR |= (uint32_t) 0b01<<(5*2);
	GPIOA->OSPEEDR |= (uint32_t) 0b11<<(5*2);
	GPIOA->BSRRL = 0b1<<5; //zapnutie led
	GPIOA->BSRRH = 0b1<<5; //vypnutie led

	//2 uloha:
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOC, ENABLE);
	GPIOC->MODER |= (uint32_t) 0b00<<(13*2);
	GPIOC->PUPDR |= (uint32_t) 0b00<<(13*2);

	/*
#define ST0 0;
#define ST1 1;
#define ST2 2;

	 */
	uint8_t cState=0;
	uint8_t in;
	uint8_t it;
	in = !(GPIOC->IDR&= (uint16_t)(1 << 13));

	switch(cState){
	case 0 :
		if(in){
			cState  = 1;
			it = 0;
		}
		break;
	case 1:
		if(in){
			it++;
			if(it>=5){
				cState = 2;
			}

		}
		else{
			cState = 0;
		}
		break;
	}




	//uint8_t in;


	/* Infinite loop */
	while (1)
	{
		i++;
		in = !(GPIOC->IDR&= (uint16_t)(1 << 13));

		switch(cState){
		case 0 :
			if(in){
				cState  = 1;
				it = 0;
			}
			break;
		case 1:
			if(in){
				it++;
				if(it>=5){
					cState = 2;
				}

			}
			else{
				cState = 0;
			}
			break;
		case 2:
			if(!in){
				it = 0;
				cState = 0;
			}
			break;
		}


		if(cState == 2){
			GPIOA->BSRRL = 0b1<<5; //zapnutie led
		}
		else {
			GPIOA->BSRRH = 0b1<<5; //vypnutie led
		}

		//3 uloha 2 cast
		/*
	in = !(GPIOC->IDR&= (uint16_t)(1 << 13));
	  if (in) {
		  GPIOA->BSRRL = 0b1<<5; //zapnutie led
	}
	  else{
		  GPIOA->BSRRH = 0b1<<5; //vypnutie led
	  }
		 */
		//3 uloha, 1 cast - pustat vo while
		/*
	GPIOA->BSRRL = 0b1<<5; //zapnutie led
	int var = 0;
	for (var = 0; var < 10000; ++var) {
			i++;
		}
	GPIOA->BSRRH = 0b1<<5; //vypnutie led

	for (var = 0; var < 50000; ++var) {
			  i= i + 5*2 - 3*2;

		}
		 */

	}
	return 0;
}

#ifdef  USE_FULL_ASSERT

/**
 * @brief  Reports the name of the source file and the source line number
 *   where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t* file, uint32_t line)
{
	/* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

	/* Infinite loop */
	while (1)
	{
	}
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
	while(1)
	{}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
	__assert_func (file, line, NULL, failedexpr);
}
